name: "ROS Distro Status"
on:
  pull_request:

jobs:
  check_status:
    name: "Check ROS Distro Status"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: rosdistro
      - uses: actions/checkout@v2
        with:
          repository: mjcarroll/rosdistro_status
          path: rosdistro_status
      - uses: mjcarroll/action-rosdistro-status@releases/v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

