name: "rosdistro"
on:
  pull_request:
    paths:
      - ardent/distribution.yaml
      - bouncy/distribution.yaml
      - crystal/distribution.yaml
      - dashing/distribution.yaml
      - eloquent/distribution.yaml
      - foxy/distribution.yaml
      - groovy/distribution.yaml
      - indigo/distribution.yaml
      - jade/distribution.yaml
      - kinetic/distribution.yaml
      - lunar/distribution.yaml
      - melodic/distribution.yaml
      - noetic/distribution.yaml
  schedule:
    - cron:  '5 * * * *'

jobs:
  single_distro:
    name: "Modifies Single Distro"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: rosdistro
      - uses: actions/checkout@v2
        with:
          repository: mjcarroll/rosdistro_status
          path: rosdistro_status
      - uses: mjcarroll/action-rosdistro-status@releases/v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          checks: 'single_distro'
  check_eol:
    name: "Is Not EOL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: rosdistro
      - uses: actions/checkout@v2
        with:
          repository: mjcarroll/rosdistro_status
          path: rosdistro_status
      - uses: mjcarroll/action-rosdistro-status@releases/v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          checks: 'eol'
  check_distro:
    name: "Distro Held for Sync"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: rosdistro
      - uses: actions/checkout@v2
        with:
          repository: mjcarroll/rosdistro_status
          path: rosdistro_status
      - uses: mjcarroll/action-rosdistro-status@releases/v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          checks: 'distro_freeze'
  check_type:
    name: "Type (ROS1/ROS2) Held for Buildfarm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: rosdistro
      - uses: actions/checkout@v2
        with:
          repository: mjcarroll/rosdistro_status
          path: rosdistro_status
      - uses: mjcarroll/action-rosdistro-status@releases/v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          checks: 'ros_freeze'
      

